import Head from "next/head"
import Navbar from "@/components/Navbar"
import Hero from "@/components/Hero"
import Company from "@/components/Company"
import Services from "@/components/Services"
import Machines from "@/components/Machines"
import Contact from "@/components/Contact"
import Footer from "@/components/Footer"

export default function Home() {
  return (
    <>
      <Head>
        <title>Jass ATM Sales & Service</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Company />
        <Services />
        <Machines />
        <Contact />
        <Footer />
      </main>
    </>
  )
}
