import Head from "next/head"
import Image from "next/image"

import Navbar from "@/components/Navbar"
import Hero from "@/components/Hero"
import Company from "@/components/Company"
import Services from "@/components/Services"

export default function Home() {
  return (
    <>
      <Head>
        <title>Jass ATM Sales & Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Company />
        <Services />
      </main>
    </>
  )
}
